code --install-extension abusaidm.html-snippets
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension fabiospampinato.vscode-open-in-application
code --install-extension felixfbecker.php-debug
code --install-extension fterrag.vscode-php-cs-fixer
code --install-extension Gruntfuggly.todo-tree
code --install-extension ikappas.composer
code --install-extension jebbs.plantuml
code --install-extension jesschadwick.nuget-reverse-package-search
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension joaompinto.asciidoctor-vscode
code --install-extension junstyle.php-cs-fixer
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mrmlnc.vscode-scss
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-dotnettools.csharp
code --install-extension mtxr.sqltools
code --install-extension neilbrayfield.php-docblocker
code --install-extension oderwat.indent-rainbow
code --install-extension onecentlin.laravel-blade
code --install-extension phplasma.csv-to-table
code --install-extension phproberto.vscode-php-getters-setters
code --install-extension ryannaddy.laravel-artisan
code --install-extension shardulm94.trailing-spaces
code --install-extension shuworks.vscode-table-formatter
code --install-extension sohamkamani.code-eol
code --install-extension visualzoran.vz-file-templates
code --install-extension vscodevim.vim
code --install-extension wmaurer.change-case
code --install-extension Zignd.html-css-class-completion
